#!/usr/bin/env node
// Bundle one or more store.json files into worker/src/catalog.js, the Worker's only source
// of prices and Printful ids:  node worker/make-catalog.mjs ../site-a/store.json ../site-b/store.json
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export function slimStore(s) {
  if (!s.printfulStoreId) throw new Error(`${s.id}: printfulStoreId is required for checkout`);
  return {
    id: s.id, url: s.url, currency: s.currency || 'USD', printfulStoreId: s.printfulStoreId,
    pieces: s.pieces.map((p) => ({
      slug: p.slug, name: p.name, price: p.price,
      image: p.images?.[0] ? new URL(p.images[0].src, s.url).href : null,
      variants: (p.variants || []).map((v) => ({ id: v.id, label: v.label || Object.values(v.options || {}).join(' / '), price: v.price })),
    })),
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const files = process.argv.slice(2);
  if (!files.length) { console.error('usage: node worker/make-catalog.mjs STORE_JSON...'); process.exit(2); }
  const cat = {};
  for (const f of files) { const s = slimStore(JSON.parse(readFileSync(f, 'utf8'))); cat[s.id] = s; }
  const out = join(dirname(fileURLToPath(import.meta.url)), 'src', 'catalog.js');
  writeFileSync(out, `// Generated by worker/make-catalog.mjs. Do not edit.\nexport default ${JSON.stringify(cat, null, 1)};\n`);
  console.log(`wrote ${out}: ${Object.keys(cat).join(', ')}`);
}
